import os
import base64
import logging
from datetime import date, timedelta
from pathlib import Path

import requests

log = logging.getLogger(__name__)


def send_wages_email(file_path: str, summary: dict, target_sunday: date = None):
    """Email the updated wages file with a run summary."""
    api_key    = os.getenv('SENDGRID_API_KEY')
    to_email   = os.getenv('EMAIL_TO', 'yuvi@memoryblock.com.au')
    from_email = os.getenv('EMAIL_FROM', 'wages@memoryblock.com.au')

    if not api_key:
        log.warning("SENDGRID_API_KEY not set — skipping email")
        return

    if target_sunday is None:
        from square_service import get_previous_week_sunday
        target_sunday = get_previous_week_sunday()

    week_start = target_sunday - timedelta(days=6)
    subject    = f"MB Ireland Wages — {week_start.strftime('%d %b')} to {target_sunday.strftime('%d %b %Y')}"

    rows = []
    for location, data in summary.items():
        if 'error' in data:
            rows.append(f"""
            <tr style="background:#fff3cd">
              <td style="padding:8px 12px;font-weight:bold">{location}</td>
              <td colspan="3" style="padding:8px 12px;color:#856404">{data['error']}</td>
            </tr>""")
            continue

        updated   = data.get('updated', [])
        unmatched = data.get('unmatched', [])
        note      = data.get('note', '')

        if note:
            rows.append(f"""
            <tr>
              <td style="padding:8px 12px;font-weight:bold">{location}</td>
              <td colspan="3" style="padding:8px 12px;color:#6c757d">{note}</td>
            </tr>""")
            continue

        income      = data.get('income', 0.0)
        income_html = f"<div style='font-size:13px;font-weight:bold;color:#2c7a2c;margin-bottom:6px'>Income: €{income:,.2f}</div>" if income else ''

        staff_lines = ''.join(
            f"<div style='margin:2px 0;font-size:13px'>{u['name']}: "
            f"{u['weekday_hours']}h Mon-Sat, {u['sunday_hours']}h Sun</div>"
            for u in updated
        )
        unmatched_html = (
            f"<div style='color:#dc3545;font-size:12px;margin-top:4px'>"
            f"⚠ Unmatched in Square: {', '.join(unmatched)}</div>"
        ) if unmatched else ''

        added     = data.get('added', [])
        added_html = (
            f"<div style='color:#856404;font-size:12px;margin-top:4px'>"
            f"★ New staff added (default rates — check & adjust): {', '.join(added)}</div>"
        ) if added else ''

        rows.append(f"""
        <tr>
          <td style="padding:8px 12px;font-weight:bold;vertical-align:top">{location}</td>
          <td style="padding:8px 12px;vertical-align:top">{len(updated)} staff</td>
          <td style="padding:8px 12px">{income_html}{staff_lines}{unmatched_html}{added_html}</td>
        </tr>""")

    html_body = f"""
    <div style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto">
      <h2 style="color:#2c3e50;border-bottom:2px solid #e9ecef;padding-bottom:10px">
        Memory Block Ireland — Weekly Wages
      </h2>
      <p style="color:#495057">
        <strong>Week:</strong> {week_start.strftime('%d %b %Y')} – {target_sunday.strftime('%d %b %Y')}
      </p>
      <p>The file is attached. Check for any unmatched staff, add bonuses or adjustments (columns V, W), then process payments.</p>

      <table style="width:100%;border-collapse:collapse;margin-top:16px">
        <thead>
          <tr style="background:#343a40;color:#fff">
            <th style="padding:10px 12px;text-align:left;width:160px">Location</th>
            <th style="padding:10px 12px;text-align:left;width:80px">Staff</th>
            <th style="padding:10px 12px;text-align:left">Detail</th>
          </tr>
        </thead>
        <tbody>{''.join(rows)}</tbody>
      </table>

      <p style="color:#adb5bd;font-size:11px;margin-top:24px">
        Auto-generated by MB Ireland Wages System · Do not reply to this email
      </p>
    </div>
    """

    with open(file_path, 'rb') as f:
        file_data = base64.b64encode(f.read()).decode()

    payload = {
        "personalizations": [{"to": [{"email": to_email}]}],
        "from": {"email": from_email, "name": "MB Ireland Wages"},
        "subject": subject,
        "content": [{"type": "text/html", "value": html_body}],
        "attachments": [{
            "content":  file_data,
            "type":     "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "filename": Path(file_path).name,
        }],
    }

    r = requests.post(
        'https://api.sendgrid.com/v3/mail/send',
        json=payload,
        headers={'Authorization': f'Bearer {api_key}', 'Content-Type': 'application/json'},
    )

    if r.status_code == 202:
        log.info(f"Wages email sent to {to_email}")
    else:
        log.error(f"SendGrid error {r.status_code}: {r.text}")
